### ISSUE TITLE
Split `engine.py`

### ISSUE THREAD

**Issue by betodealmeida** [DataJunction/datajunction#93]
`engine.py` has a lot of logic that is not related to executing queries. We should move the functions `get_query_for_node` and `get_query_for_sql` (as well as associated functions) to a new file `sql/build.py`, since they are used to build queries from a node or from SQL.

**Comment by zzzzz1st** [comment]
I'll give that a try.

**Comment by betodealmeida** [comment]
Thanks, @zzzzz1st! I'll take a look at your PR. Feel free to reach out if you have any questions, I'm still working on the developer docs.
